'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DashBoard
    
    '''<summary>
    '''lblUserNameMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserNameMenu As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUserRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserRole As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSidebarUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSidebarUserName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSideBarUserDesig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSideBarUserDesig As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dashboard As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''account control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents account As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''transaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents transaction As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''analysis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents analysis As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''settings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents settings As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblBoxValue1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBoxValue1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBoxText1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBoxText1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBoxValue2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBoxValue2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBoxText2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBoxText2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBoxValue3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBoxValue3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBoxText3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBoxText3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBoxValue4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBoxValue4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBoxText4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBoxText4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBox1T control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBox1T As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBox1M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBox1M As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBox1B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBox1B As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBox2T control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBox2T As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBox2M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBox2M As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBox2B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBox2B As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''profitUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents profitUp As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblBox3Tup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBox3Tup As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''profitDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents profitDown As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblBox3Tdn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBox3Tdn As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBox3M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBox3M As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBox3B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBox3B As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBox4T control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBox4T As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBox4M control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBox4M As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBox4B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBox4B As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInventoryValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInventoryValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInvProgVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvProgVal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblInvProgDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvProgDesc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAccValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccValue As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAccProgVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccProgVal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAccProgDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccProgDesc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSalesVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSalesVal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSaleProgVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaleProgVal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSaleProgDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaleProgDesc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPurcVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPurcVal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPurcProgVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPurcProgVal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPurcProgDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPurcProgDesc As Global.System.Web.UI.WebControls.Label
End Class
